default:
  app_name: "Sample_App"
  version: "1.0.0"

help:
  h: "http://www.railstutorial.org/help"
  b: "http://www.railstutorial.org/book"

home:
  guide: "https://guides.rubyonrails.org/"

models:
  user:
    name_length: 50
    email_length: 255

digits:
  digit_6: 6

page_10: 10

gravatar:
  size: 80
  view_size: 50
  link: "https://gravatar.com/emails"

expired_time: 2
